In [1]:
import pandas as pd

In [1]:
df=pd.read_excel("Finance_sheet.xlsx")
df

NameError: name 'pd' is not defined

In [4]:
print("Top 5 Records")
print(df.head())                # First 5 rows
print("Bottom 5 Records")
print(df.tail())                # Last 5 rows
print("Shape")
print(df.shape)                 # (rows, columns)
print("Column Name")
print(df.columns)               # Column names
print("Data Type and Non Null Values")
print(df.info())                # Data types and non-null values
print("Data Types")
print(df.dtypes)                # Data types per column

Top 5 Records
    ID             NAME  GENDER      ADDRESS  AADHAR     CONTACT   BANK Loan  \
0  111      Emily Davis  Female   Jankipuram  294808  7959625976    SBI   PL
1  112    Theodore Dinh    Male  Gomti Nagar  397766  8443967479   HDFC   HL
2  113     Luna Sanders  Female     Aminabad  285006  8260860045    PNB   CL
3  114  Penelope Jordan  Female    Aashiyana  378034  8307547251    BOB   EL
4  115        Austin Vo    Male   Jankipuram  314090  7686296906  ICICI   GL

   Rate  TIME  AMOUNT          EMI
0  0.18     3   85412  3087.848408
1  0.18     5   52731  1339.020822
2  0.12     2   87118  4100.946753
3  0.11     9   85813  1255.089012
4  0.20     7   46851  1040.382643
Bottom 5 Records
     ID            NAME  GENDER      ADDRESS  AADHAR     CONTACT    BANK Loan  \
45  156  Gabriel Holmes    Male  Gomti Nagar  336436  8306537926     YES   PL
46  157     Wyatt Rojas    Male     Aminabad  247886  7885034254   UNION   HL
47  158     Eva Coleman  Female    Aashiyana  270828  8772917989  KOTAK    CL
48  159   Dominic Clark    Male   Jankipuram  236476  7398487833     SBI   EL
49  160  Lucy Alexander  Female  Gomti Nagar  385317  7540127982    HDFC   GL

    Rate  TIME  AMOUNT          EMI
45  0.20     5   74156  1964.680441
46  0.20    10   62010  1198.378423
47  0.20     8   55000  1152.426020
48  0.18     2   86452  4316.038463
49  0.18     3   80110  2896.168406
Shape
(50, 12)
Column Name
Index(['ID', 'NAME', 'GENDER', 'ADDRESS', 'AADHAR', 'CONTACT', 'BANK', 'Loan',
       'Rate', 'TIME', 'AMOUNT', 'EMI'],
      dtype='object')
Data Type and Non Null Values
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       50 non-null     int64
 1   NAME     50 non-null     object
 2   GENDER   50 non-null     object
 3   ADDRESS  50 non-null     object
 4   AADHAR   50 non-null     int64
 5   CONTACT  50 non-null     int64
 6   BANK     50 non-null     object
 7   Loan     50 non-null     object
 8   Rate     50 non-null     float64
 9   TIME     50 non-null     int64
 10  AMOUNT   50 non-null     int64
 11  EMI      50 non-null     float64
dtypes: float64(2), int64(5), object(5)
memory usage: 4.8+ KB
None
Data Types
ID           int64
NAME        object
GENDER      object
ADDRESS     object
AADHAR       int64
CONTACT      int64
BANK        object
Loan        object
Rate       float64
TIME         int64
AMOUNT       int64
EMI        float64
dtype: object

In [5]:
#Data Cleaning
df.isnull().sum()

ID         0
NAME       0
GENDER     0
ADDRESS    0
AADHAR     0
CONTACT    0
BANK       0
Loan       0
Rate       0
TIME       0
AMOUNT     0
EMI        0
dtype: int64

In [6]:
df.dropna()

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3087.848408
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.020822
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4100.946753
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.089012
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.382643
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.093588
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,939.944004
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4755.907382
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.402904
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1712.953795
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4087.672034
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,430.510110
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2321.891147
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8903.658169
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.443634
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.086178
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.367450
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3243.629080
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1170.591653
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.255615
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1672.743796
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.022395
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.401768
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.235166
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,984.905417
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2503.893410
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,793.570671
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,917.921617
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.211918
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1744.963140
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.214803
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,965.544426
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.048677
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,979.684946
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.075800
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,532.725803
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.169824
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.390630
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8270.871859
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1677.972952
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,559.843433
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.228556
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.082003
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.185753
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.280171
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1964.680441
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.378423
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.426020
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.038463
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.168406

In [7]:
df.fillna(0)

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3087.848408
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.020822
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4100.946753
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.089012
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.382643
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.093588
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,939.944004
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4755.907382
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.402904
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1712.953795
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4087.672034
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,430.510110
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2321.891147
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8903.658169
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.443634
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.086178
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.367450
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3243.629080
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1170.591653
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.255615
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1672.743796
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.022395
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.401768
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.235166
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,984.905417
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2503.893410
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,793.570671
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,917.921617
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.211918
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1744.963140
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.214803
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,965.544426
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.048677
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,979.684946
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.075800
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,532.725803
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.169824
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.390630
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8270.871859
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1677.972952
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,559.843433
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.228556
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.082003
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.185753
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.280171
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1964.680441
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.378423
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.426020
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.038463
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.168406

In [10]:
df['CONTACT'] = df['CONTACT'].astype(str)
df

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3087.848408
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.020822
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4100.946753
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.089012
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.382643
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.093588
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,939.944004
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4755.907382
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.402904
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1712.953795
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4087.672034
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,430.510110
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2321.891147
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8903.658169
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.443634
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.086178
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.367450
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3243.629080
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1170.591653
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.255615
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1672.743796
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.022395
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.401768
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.235166
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,984.905417
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2503.893410
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,793.570671
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,917.921617
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.211918
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1744.963140
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.214803
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,965.544426
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.048677
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,979.684946
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.075800
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,532.725803
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.169824
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.390630
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8270.871859
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1677.972952
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,559.843433
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.228556
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.082003
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.185753
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.280171
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1964.680441
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.378423
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.426020
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.038463
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.168406

In [11]:
df.columns = df.columns.str.strip() # Strip column names of whitespace
df

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3087.848408
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.020822
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4100.946753
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.089012
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.382643
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.093588
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,939.944004
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4755.907382
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.402904
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1712.953795
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4087.672034
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,430.510110
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2321.891147
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8903.658169
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.443634
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.086178
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.367450
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3243.629080
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1170.591653
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.255615
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1672.743796
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.022395
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.401768
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.235166
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,984.905417
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2503.893410
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,793.570671
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,917.921617
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.211918
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1744.963140
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.214803
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,965.544426
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.048677
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,979.684946
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.075800
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,532.725803
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.169824
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.390630
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8270.871859
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1677.972952
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,559.843433
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.228556
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.082003
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.185753
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.280171
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1964.680441
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.378423
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.426020
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.038463
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.168406

In [12]:
#Accessing Data
df['NAME']               # Access column
df[['NAME', 'GENDER']]   # Access multiple columns
df.iloc[0]               # First row
df.loc[0, 'NAME']        # Value from row 0, column 'NAME'
df[df['GENDER'] == 'Male']   # Filter condition

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.020822
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.382643
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.093588
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4755.907382
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.402904
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2321.891147
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.443634
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1170.591653
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.255615
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1672.743796
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.401768
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.235166
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,984.905417
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2503.893410
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,917.921617
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.211918
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1744.963140
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.214803
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,965.544426
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.048677
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,979.684946
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.390630
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,559.843433
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.082003
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.185753
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1964.680441
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.378423
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.038463

In [13]:
#Grouping and Aggregation
df.groupby('GENDER').size()                             # Count per gender
df.groupby('BANK')['AMOUNT'].sum()                      # Total amount per bank
df.groupby(['BANK', 'GENDER'])['AMOUNT'].mean()         # Avg amount by bank and gender

BANK    GENDER
BOB     Female    48351.333333
        Male      52865.666667
HDFC    Female    72760.500000
        Male      52418.666667
ICICI   Female    33267.500000
        Male      82143.000000
KOTAK   Female    61323.666667
        Male      64729.333333
PNB     Female    70767.250000
        Male      56925.500000
SBI     Female    81506.000000
        Male      48371.000000
UNION   Female    65806.500000
        Male      68464.000000
YES     Female    91740.000000
        Male      57935.500000
Name: AMOUNT, dtype: float64

In [14]:
#Sorting and Filtering
df.sort_values('AMOUNT', ascending=False)               # Sort by amount
df[df['AMOUNT'] > 100000]                               # Filter high loans
df[(df['GENDER'] == 'Female') & (df['AMOUNT'] > 50000)] # Multiple filters

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3087.848408
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4100.946753
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.089012
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1712.953795
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4087.672034
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8903.658169
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.086178
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.367450
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3243.629080
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.022395
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.075800
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8270.871859
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.426020
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.168406

In [16]:
#Creating New Columns
df['Interest'] = (df['AMOUNT'] * df['Rate'] * df['TIME']) / 100  # Simple interest
df['Full_Name'] = df['NAME'].str.upper() 
df

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3087.848408,461.2248,EMILY DAVIS
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.020822,474.5790,THEODORE DINH
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4100.946753,209.0832,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.089012,849.5487,PENELOPE JORDAN
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.382643,655.9140,AUSTIN VO
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.093588,247.6720,JOSHUA GUPTA
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,939.944004,592.5920,RUBY BARNES
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4755.907382,373.7760,LUKE MARTIN
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.402904,186.7698,EASTON BAILEY
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1712.953795,1026.9000,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4087.672034,208.4064,SAVANNAH ALI
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,430.510110,343.7830,CAMILA ROGERS
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2321.891147,1163.2320,ELI JONES
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8903.658169,192.2320,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.443634,401.0320,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.086178,335.2800,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.367450,139.6800,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3243.629080,484.4934,CAMILA SILVA
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1170.591653,213.3696,DAVID BARNES
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.255615,363.0000,ADAM DANG
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1672.743796,1731.1200,ELIAS ALVARADO
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.022395,1223.0960,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.401768,162.3240,LOGAN RIVERA
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.235166,546.6300,LEONARDO DIXON
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,984.905417,850.6458,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2503.893410,180.5544,JOSE HENDERSON
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,793.570671,214.0500,ABIGAIL MEJIA
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,917.921617,232.1990,WYATT CHIN
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.211918,1571.6640,CARSON LU
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1744.963140,1100.1200,DYLAN CHOI
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.214803,805.5500,EZEKIEL KUMAR
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,965.544426,737.2960,DOMINIC GUZMAN
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.048677,71.8596,ANGEL POWELL
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,979.684946,978.6780,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.075800,176.2560,CAROLINE JENKINS
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,532.725803,184.7208,NORA BROWN
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.169824,472.9480,ADELINE HUANG
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.390630,192.1880,JACKSON PERRY
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8270.871859,178.5700,RILEY PADILLA
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1677.972952,270.9060,LEAH PENA
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,559.843433,408.7440,OWEN LAM
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.228556,571.8384,KENNEDY FOSTER
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.082003,582.9516,JOHN MOORE
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.185753,298.1352,WILLIAM VU
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.280171,524.0480,SADIE WASHINGTON
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1964.680441,741.5600,GABRIEL HOLMES
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.378423,1240.2000,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.426020,880.0000,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.038463,311.2272,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.168406,432.5940,LUCY ALEXANDER

In [17]:
#Value Counts and Unique Values
df['BANK'].value_counts()       # Count of records per bank
df['GENDER'].unique()           # Unique values in GENDER
df['GENDER'].nunique()          # Number of unique genders

2

In [18]:
#Pivot Tables
pd.pivot_table(df, values='AMOUNT', index='BANK', columns='GENDER', aggfunc='sum')

GENDER  Female    Male
BANK
BOB     145054  158597
HDFC    291042  157256
ICICI    66535  328572
KOTAK   183971  194188
PNB     283069  113851
SBI     163012  241855
UNION   131613  273856
YES     183480  231742

In [19]:
#Correlation and Stats
df.corr(numeric_only=True)     # Correlation between numeric fields
df['AMOUNT'].mean()            # Average loan amount
df['AMOUNT'].max()             # Max loan amount

np.int64(98229)

In [20]:
#Handling Duplicates
df.duplicated().sum()          # Count of duplicates
df.drop_duplicates()           # Remove duplicates

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3087.848408,461.2248,EMILY DAVIS
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.020822,474.5790,THEODORE DINH
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4100.946753,209.0832,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.089012,849.5487,PENELOPE JORDAN
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.382643,655.9140,AUSTIN VO
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.093588,247.6720,JOSHUA GUPTA
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,939.944004,592.5920,RUBY BARNES
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4755.907382,373.7760,LUKE MARTIN
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.402904,186.7698,EASTON BAILEY
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1712.953795,1026.9000,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4087.672034,208.4064,SAVANNAH ALI
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,430.510110,343.7830,CAMILA ROGERS
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2321.891147,1163.2320,ELI JONES
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8903.658169,192.2320,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.443634,401.0320,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.086178,335.2800,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.367450,139.6800,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3243.629080,484.4934,CAMILA SILVA
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1170.591653,213.3696,DAVID BARNES
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.255615,363.0000,ADAM DANG
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1672.743796,1731.1200,ELIAS ALVARADO
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.022395,1223.0960,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.401768,162.3240,LOGAN RIVERA
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.235166,546.6300,LEONARDO DIXON
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,984.905417,850.6458,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2503.893410,180.5544,JOSE HENDERSON
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,793.570671,214.0500,ABIGAIL MEJIA
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,917.921617,232.1990,WYATT CHIN
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.211918,1571.6640,CARSON LU
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1744.963140,1100.1200,DYLAN CHOI
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.214803,805.5500,EZEKIEL KUMAR
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,965.544426,737.2960,DOMINIC GUZMAN
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.048677,71.8596,ANGEL POWELL
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,979.684946,978.6780,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.075800,176.2560,CAROLINE JENKINS
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,532.725803,184.7208,NORA BROWN
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.169824,472.9480,ADELINE HUANG
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.390630,192.1880,JACKSON PERRY
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8270.871859,178.5700,RILEY PADILLA
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1677.972952,270.9060,LEAH PENA
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,559.843433,408.7440,OWEN LAM
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.228556,571.8384,KENNEDY FOSTER
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.082003,582.9516,JOHN MOORE
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.185753,298.1352,WILLIAM VU
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.280171,524.0480,SADIE WASHINGTON
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1964.680441,741.5600,GABRIEL HOLMES
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.378423,1240.2000,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.426020,880.0000,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.038463,311.2272,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.168406,432.5940,LUCY ALEXANDER

In [21]:
#Common Analytics Use-Cases
#1.Total loan disbursed
df['AMOUNT'].sum()

np.int64(3147693)

In [23]:
#Number of loans per bank	
df['BANK'].value_counts()

BANK
SBI       7
HDFC      7
PNB       6
BOB       6
ICICI     6
YES       6
UNION     6
KOTAK     6
Name: count, dtype: int64

In [24]:
#Gender distribution
df['GENDER'].value_counts()

GENDER
Male      28
Female    22
Name: count, dtype: int64

In [25]:
#Average EMI by bank
df.groupby('BANK')['EMI'].mean()

BANK
BOB        966.781318
HDFC      1922.654145
ICICI     1421.613250
KOTAK     2377.695354
PNB       2472.489819
SBI       2996.207822
UNION     3597.875748
YES       2990.134727
Name: EMI, dtype: float64

In [28]:
#ROUND THE VALUES
df['EMI'] = df['EMI'].round(2)
df

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3087.85,461.2248,EMILY DAVIS
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.02,474.5790,THEODORE DINH
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4100.95,209.0832,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.09,849.5487,PENELOPE JORDAN
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.38,655.9140,AUSTIN VO
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.09,247.6720,JOSHUA GUPTA
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,939.94,592.5920,RUBY BARNES
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4755.91,373.7760,LUKE MARTIN
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.40,186.7698,EASTON BAILEY
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1712.95,1026.9000,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4087.67,208.4064,SAVANNAH ALI
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,430.51,343.7830,CAMILA ROGERS
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2321.89,1163.2320,ELI JONES
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8903.66,192.2320,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.44,401.0320,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.09,335.2800,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.37,139.6800,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3243.63,484.4934,CAMILA SILVA
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1170.59,213.3696,DAVID BARNES
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.26,363.0000,ADAM DANG
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1672.74,1731.1200,ELIAS ALVARADO
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.02,1223.0960,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.40,162.3240,LOGAN RIVERA
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.24,546.6300,LEONARDO DIXON
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,984.91,850.6458,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2503.89,180.5544,JOSE HENDERSON
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,793.57,214.0500,ABIGAIL MEJIA
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,917.92,232.1990,WYATT CHIN
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.21,1571.6640,CARSON LU
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1744.96,1100.1200,DYLAN CHOI
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.21,805.5500,EZEKIEL KUMAR
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,965.54,737.2960,DOMINIC GUZMAN
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.05,71.8596,ANGEL POWELL
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,979.68,978.6780,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.08,176.2560,CAROLINE JENKINS
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,532.73,184.7208,NORA BROWN
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.17,472.9480,ADELINE HUANG
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.39,192.1880,JACKSON PERRY
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8270.87,178.5700,RILEY PADILLA
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1677.97,270.9060,LEAH PENA
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,559.84,408.7440,OWEN LAM
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.23,571.8384,KENNEDY FOSTER
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.08,582.9516,JOHN MOORE
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.19,298.1352,WILLIAM VU
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.28,524.0480,SADIE WASHINGTON
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1964.68,741.5600,GABRIEL HOLMES
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.38,1240.2000,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.43,880.0000,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.04,311.2272,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.17,432.5940,LUCY ALEXANDER

In [30]:
#Round of Multiple Columns
df = df.round({
    'Rate': 2,
    'AMOUNT': 0,
    'EMI': 0
})
df

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3088.0,461.2248,EMILY DAVIS
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.0,474.5790,THEODORE DINH
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4101.0,209.0832,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.0,849.5487,PENELOPE JORDAN
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.0,655.9140,AUSTIN VO
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.0,247.6720,JOSHUA GUPTA
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,940.0,592.5920,RUBY BARNES
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4756.0,373.7760,LUKE MARTIN
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.0,186.7698,EASTON BAILEY
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.9000,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4088.0,208.4064,SAVANNAH ALI
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,431.0,343.7830,CAMILA ROGERS
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2322.0,1163.2320,ELI JONES
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8904.0,192.2320,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.0,401.0320,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.0,335.2800,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.0,139.6800,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.4934,CAMILA SILVA
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1171.0,213.3696,DAVID BARNES
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.0,363.0000,ADAM DANG
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1673.0,1731.1200,ELIAS ALVARADO
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.0,1223.0960,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.0,162.3240,LOGAN RIVERA
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.0,546.6300,LEONARDO DIXON
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,985.0,850.6458,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.5544,JOSE HENDERSON
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,794.0,214.0500,ABIGAIL MEJIA
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,918.0,232.1990,WYATT CHIN
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.0,1571.6640,CARSON LU
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1745.0,1100.1200,DYLAN CHOI
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.0,805.5500,EZEKIEL KUMAR
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,966.0,737.2960,DOMINIC GUZMAN
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.0,71.8596,ANGEL POWELL
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,980.0,978.6780,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.0,176.2560,CAROLINE JENKINS
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,533.0,184.7208,NORA BROWN
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.0,472.9480,ADELINE HUANG
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.0,192.1880,JACKSON PERRY
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8271.0,178.5700,RILEY PADILLA
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1678.0,270.9060,LEAH PENA
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,560.0,408.7440,OWEN LAM
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.0,571.8384,KENNEDY FOSTER
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.0,582.9516,JOHN MOORE
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.0,298.1352,WILLIAM VU
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.0,524.0480,SADIE WASHINGTON
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1965.0,741.5600,GABRIEL HOLMES
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.0,1240.2000,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.0,880.0000,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.0,311.2272,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.5940,LUCY ALEXANDER

In [31]:
#Round While Creating a New Column
#For example, if you're calculating interest:
df['Interest'] = ((df['AMOUNT'] * df['Rate'] * df['TIME']) / 100).round(2)
df

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3088.0,461.22,EMILY DAVIS
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.0,474.58,THEODORE DINH
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4101.0,209.08,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.0,849.55,PENELOPE JORDAN
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.0,655.91,AUSTIN VO
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.0,247.67,JOSHUA GUPTA
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,940.0,592.59,RUBY BARNES
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4756.0,373.78,LUKE MARTIN
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.0,186.77,EASTON BAILEY
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4088.0,208.41,SAVANNAH ALI
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,431.0,343.78,CAMILA ROGERS
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2322.0,1163.23,ELI JONES
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8904.0,192.23,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.0,401.03,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.0,335.28,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.0,139.68,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1171.0,213.37,DAVID BARNES
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.0,363.00,ADAM DANG
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1673.0,1731.12,ELIAS ALVARADO
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.0,1223.10,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.0,162.32,LOGAN RIVERA
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.0,546.63,LEONARDO DIXON
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,985.0,850.65,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.55,JOSE HENDERSON
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,794.0,214.05,ABIGAIL MEJIA
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,918.0,232.20,WYATT CHIN
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.0,1571.66,CARSON LU
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1745.0,1100.12,DYLAN CHOI
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.0,805.55,EZEKIEL KUMAR
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,966.0,737.30,DOMINIC GUZMAN
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.0,71.86,ANGEL POWELL
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,980.0,978.68,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.0,176.26,CAROLINE JENKINS
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,533.0,184.72,NORA BROWN
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.0,472.95,ADELINE HUANG
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.0,192.19,JACKSON PERRY
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8271.0,178.57,RILEY PADILLA
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1678.0,270.91,LEAH PENA
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,560.0,408.74,OWEN LAM
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.0,571.84,KENNEDY FOSTER
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.0,582.95,JOHN MOORE
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.0,298.14,WILLIAM VU
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.0,524.05,SADIE WASHINGTON
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1965.0,741.56,GABRIEL HOLMES
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.0,1240.20,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.0,880.00,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.0,311.23,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER

In [33]:
#Use of Logical Operator in Pandas
df[(df['GENDER'] == 'Female') & (df['BANK'] == 'HDFC')]

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.0,571.84,KENNEDY FOSTER
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER

In [34]:
#Filter: Customers whose name starts with "A"
df[df['NAME'].str.startswith('A')]

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.0,655.91,AUSTIN VO
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.0,363.00,ADAM DANG
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,794.0,214.05,ABIGAIL MEJIA
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.0,71.86,ANGEL POWELL
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.0,472.95,ADELINE HUANG

In [35]:
#Storing the Filtered Data
filtered_df = df[(df['BANK'] == 'SBI') & (df['Rate'] < 10)]
filtered_df.to_excel('sbi_low_rate_loans.xlsx', index=False)

In [36]:
#Negation Example (NOT)
#Get all records except those with time period = 5 years:
df[~(df['TIME'] == 5)]

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3088.0,461.22,EMILY DAVIS
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4101.0,209.08,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.0,849.55,PENELOPE JORDAN
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI,GL,0.20,7,46851,1040.0,655.91,AUSTIN VO
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.0,247.67,JOSHUA GUPTA
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,940.0,592.59,RUBY BARNES
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4756.0,373.78,LUKE MARTIN
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.0,186.77,EASTON BAILEY
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4088.0,208.41,SAVANNAH ALI
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,431.0,343.78,CAMILA ROGERS
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2322.0,1163.23,ELI JONES
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8904.0,192.23,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.0,401.03,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.0,335.28,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.0,139.68,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1171.0,213.37,DAVID BARNES
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.0,363.00,ADAM DANG
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1673.0,1731.12,ELIAS ALVARADO
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.0,1223.10,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.0,162.32,LOGAN RIVERA
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,985.0,850.65,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.55,JOSE HENDERSON
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.0,1571.66,CARSON LU
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1745.0,1100.12,DYLAN CHOI
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,966.0,737.30,DOMINIC GUZMAN
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.0,71.86,ANGEL POWELL
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,980.0,978.68,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.0,176.26,CAROLINE JENKINS
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,533.0,184.72,NORA BROWN
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI,HL,0.20,7,33782,750.0,472.95,ADELINE HUANG
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.0,192.19,JACKSON PERRY
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8271.0,178.57,RILEY PADILLA
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1678.0,270.91,LEAH PENA
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,560.0,408.74,OWEN LAM
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.0,571.84,KENNEDY FOSTER
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.0,582.95,JOHN MOORE
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.0,298.14,WILLIAM VU
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI,GL,0.20,8,32753,686.0,524.05,SADIE WASHINGTON
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.0,1240.20,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.0,880.00,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.0,311.23,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER

In [37]:
#Not from ICICI bank
df[df['BANK'] != 'ICICI']

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3088.0,461.22,EMILY DAVIS
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.0,474.58,THEODORE DINH
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4101.0,209.08,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.0,849.55,PENELOPE JORDAN
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.0,247.67,JOSHUA GUPTA
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,940.0,592.59,RUBY BARNES
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4756.0,373.78,LUKE MARTIN
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,SBI,EL,0.18,3,34587,1250.0,186.77,EASTON BAILEY
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4088.0,208.41,SAVANNAH ALI
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,431.0,343.78,CAMILA ROGERS
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8904.0,192.23,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.0,401.03,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.0,335.28,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.0,139.68,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1171.0,213.37,DAVID BARNES
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.0,363.00,ADAM DANG
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.0,1223.10,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.0,162.32,LOGAN RIVERA
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.0,546.63,LEONARDO DIXON
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,985.0,850.65,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.55,JOSE HENDERSON
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,794.0,214.05,ABIGAIL MEJIA
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,918.0,232.20,WYATT CHIN
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1745.0,1100.12,DYLAN CHOI
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.0,805.55,EZEKIEL KUMAR
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,966.0,737.30,DOMINIC GUZMAN
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,SBI,CL,0.18,1,39922,3660.0,71.86,ANGEL POWELL
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,980.0,978.68,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.0,176.26,CAROLINE JENKINS
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,533.0,184.72,NORA BROWN
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.0,192.19,JACKSON PERRY
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8271.0,178.57,RILEY PADILLA
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1678.0,270.91,LEAH PENA
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,SBI,PL,0.18,8,28385,560.0,408.74,OWEN LAM
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.0,571.84,KENNEDY FOSTER
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.0,582.95,JOHN MOORE
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.0,298.14,WILLIAM VU
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1965.0,741.56,GABRIEL HOLMES
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.0,1240.20,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.0,880.00,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.0,311.23,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER

In [38]:
#Filter: Loan between ₹50,000 and ₹1,00,000
df[(df['AMOUNT'] >= 50000) & (df['AMOUNT'] <= 100000)]

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,SBI,PL,0.18,3,85412,3088.0,461.22,EMILY DAVIS
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.0,474.58,THEODORE DINH
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4101.0,209.08,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.0,849.55,PENELOPE JORDAN
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4756.0,373.78,LUKE MARTIN
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4088.0,208.41,SAVANNAH ALI
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI,CL,0.20,6,96936,2322.0,1163.23,ELI JONES
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8904.0,192.23,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.0,401.03,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.0,335.28,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,SBI,HL,0.18,1,77600,7114.0,139.68,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.0,363.00,ADAM DANG
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI,PL,0.20,10,86556,1673.0,1731.12,ELIAS ALVARADO
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.0,1223.10,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.0,162.32,LOGAN RIVERA
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.0,546.63,LEONARDO DIXON
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,SBI,GL,0.18,9,52509,985.0,850.65,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.55,JOSE HENDERSON
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI,EL,0.20,8,98229,2058.0,1571.66,CARSON LU
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1745.0,1100.12,DYLAN CHOI
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.0,805.55,EZEKIEL KUMAR
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,980.0,978.68,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.0,176.26,CAROLINE JENKINS
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8271.0,178.57,RILEY PADILLA
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.0,582.95,JOHN MOORE
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1965.0,741.56,GABRIEL HOLMES
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.0,1240.20,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.0,880.00,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,SBI,EL,0.18,2,86452,4316.0,311.23,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER

In [39]:
#Filter: Missing Aadhar numbers
df[df['AADHAR'].isnull()]

Empty DataFrame
Columns: [ID, NAME, GENDER, ADDRESS, AADHAR, CONTACT, BANK, Loan, Rate, TIME, AMOUNT, EMI, Interest, Full_Name]
Index: []

In [41]:
#Replace Values
df['BANK'] = df['BANK'].replace({'SBI': 'State Bank of India', 'ICICI': 'ICICI Bank'})
df

,ID,NAME,GENDER,ADDRESS,AADHAR,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name
0,111,Emily Davis,Female,Jankipuram,294808,7959625976,State Bank of India,PL,0.18,3,85412,3088.0,461.22,EMILY DAVIS
1,112,Theodore Dinh,Male,Gomti Nagar,397766,8443967479,HDFC,HL,0.18,5,52731,1339.0,474.58,THEODORE DINH
2,113,Luna Sanders,Female,Aminabad,285006,8260860045,PNB,CL,0.12,2,87118,4101.0,209.08,LUNA SANDERS
3,114,Penelope Jordan,Female,Aashiyana,378034,8307547251,BOB,EL,0.11,9,85813,1255.0,849.55,PENELOPE JORDAN
4,115,Austin Vo,Male,Jankipuram,314090,7686296906,ICICI Bank,GL,0.20,7,46851,1040.0,655.91,AUSTIN VO
5,116,Joshua Gupta,Male,Gomti Nagar,344783,8835368577,YES,PL,0.20,4,30959,942.0,247.67,JOSHUA GUPTA
6,117,Ruby Barnes,Female,Aminabad,381530,8477605511,UNION,HL,0.20,7,42328,940.0,592.59,RUBY BARNES
7,118,Luke Martin,Male,Aashiyana,422648,8412513269,KOTAK,CL,0.20,2,93444,4756.0,373.78,LUKE MARTIN
8,119,Easton Bailey,Male,Jankipuram,389606,9170747068,State Bank of India,EL,0.18,3,34587,1250.0,186.77,EASTON BAILEY
9,120,Madeline Walker,Female,Gomti Nagar,262151,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER
10,121,Savannah Ali,Female,Aminabad,373567,8962904559,PNB,PL,0.12,2,86836,4088.0,208.41,SAVANNAH ALI
11,122,Camila Rogers,Female,Aashiyana,347270,9115706765,BOB,HL,0.11,10,31253,431.0,343.78,CAMILA ROGERS
12,123,Eli Jones,Male,Jankipuram,350194,9006731602,ICICI Bank,CL,0.20,6,96936,2322.0,1163.23,ELI JONES
13,124,Everleigh Ng,Female,Gomti Nagar,409793,7741714724,YES,EL,0.20,1,96116,8904.0,192.23,EVERLEIGH NG
14,125,Robert Yang,Male,Aminabad,296856,8018609222,UNION,GL,0.20,4,50129,1525.0,401.03,ROBERT YANG
15,126,Isabella Xi,Female,Aashiyana,417439,8321358880,KOTAK,PL,0.20,2,83820,4266.0,335.28,ISABELLA XI
16,127,Bella Powell,Female,Jankipuram,388284,8180559073,State Bank of India,HL,0.18,1,77600,7114.0,139.68,BELLA POWELL
17,128,Camila Silva,Female,Gomti Nagar,344410,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA
18,129,David Barnes,Male,Aminabad,422446,8271922114,PNB,EL,0.12,4,44452,1171.0,213.37,DAVID BARNES
19,130,Adam Dang,Male,Aashiyana,412357,8445337907,BOB,GL,0.11,4,82500,2132.0,363.00,ADAM DANG
20,131,Elias Alvarado,Male,Jankipuram,298394,8257217138,ICICI Bank,PL,0.20,10,86556,1673.0,1731.12,ELIAS ALVARADO
21,132,Eva Rivera,Female,Gomti Nagar,255248,8180356851,YES,HL,0.20,7,87364,1940.0,1223.10,EVA RIVERA
22,133,Logan Rivera,Male,Aminabad,254100,7828839873,UNION,CL,0.20,1,81162,7518.0,162.32,LOGAN RIVERA
23,134,Leonardo Dixon,Male,Aashiyana,411359,8069324152,KOTAK,EL,0.20,5,54663,1448.0,546.63,LEONARDO DIXON
24,135,Mateo Her,Male,Jankipuram,371548,7890486222,State Bank of India,GL,0.18,9,52509,985.0,850.65,MATEO HER
25,136,Jose Henderson,Male,Gomti Nagar,261209,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.55,JOSE HENDERSON
26,137,Abigail Mejia,Female,Aminabad,321251,7249237561,PNB,HL,0.12,5,35675,794.0,214.05,ABIGAIL MEJIA
27,138,Wyatt Chin,Male,Aashiyana,371102,8004005071,BOB,CL,0.11,5,42218,918.0,232.20,WYATT CHIN
28,139,Carson Lu,Male,Jankipuram,384280,8490807099,ICICI Bank,EL,0.20,8,98229,2058.0,1571.66,CARSON LU
29,140,Dylan Choi,Male,Gomti Nagar,331528,8582579396,YES,GL,0.20,7,78580,1745.0,1100.12,DYLAN CHOI
30,141,Ezekiel Kumar,Male,Aminabad,318540,9408619589,UNION,PL,0.20,5,80555,2134.0,805.55,EZEKIEL KUMAR
31,142,Dominic Guzman,Male,Aashiyana,421919,7469867801,KOTAK,HL,0.20,8,46081,966.0,737.30,DOMINIC GUZMAN
32,143,Angel Powell,Male,Jankipuram,378913,8992428483,State Bank of India,CL,0.18,1,39922,3660.0,71.86,ANGEL POWELL
33,144,Mateo Vu,Male,Gomti Nagar,345675,7651412039,HDFC,EL,0.18,10,54371,980.0,978.68,MATEO VU
34,145,Caroline Jenkins,Female,Aminabad,279526,8581970606,PNB,GL,0.12,2,73440,3457.0,176.26,CAROLINE JENKINS
35,146,Nora Brown,Female,Aashiyana,328626,7961188785,BOB,PL,0.11,6,27988,533.0,184.72,NORA BROWN
36,147,Adeline Huang,Female,Jankipuram,294216,9257124480,ICICI Bank,HL,0.20,7,33782,750.0,472.95,ADELINE HUANG
37,148,Jackson Perry,Male,Gomti Nagar,332499,7280368666,YES,CL,0.20,2,48047,2445.0,192.19,JACKSON PERRY
38,149,Riley Padilla,Female,Aminabad,326079,9043676825,UNION,EL,0.20,1,89285,8271.0,178.57,RILEY PADILLA
39,150,Leah Pena,Female,Aashiyana,308515,7605821528,KOTAK,GL,0.20,3,45151,1678.0,270.91,LEAH PENA
40,151,Owen Lam,Male,Jankipuram,350474,8907901812,State Bank of India,PL,0.18,8,28385,560.0,408.74,OWEN LAM
41,152,Kennedy Foster,Female,Gomti Nagar,291577,7971039531,HDFC,HL,0.18,8,39711,783.0,571.84,KENNEDY FOSTER
42,153,John Moore,Male,Aminabad,385701,8441104809,PNB,CL,0.12,7,69399,1225.0,582.95,JOHN MOORE
43,154,William Vu,Male,Aashiyana,253782,8973220080,BOB,EL,0.11,8,33879,532.0,298.14,WILLIAM VU
44,155,Sadie Washington,Female,Jankipuram,378154,9177879896,ICICI Bank,GL,0.20,8,32753,686.0,524.05,SADIE WASHINGTON
45,156,Gabriel Holmes,Male,Gomti Nagar,336436,8306537926,YES,PL,0.20,5,74156,1965.0,741.56,GABRIEL HOLMES
46,157,Wyatt Rojas,Male,Aminabad,247886,7885034254,UNION,HL,0.20,10,62010,1198.0,1240.20,WYATT ROJAS
47,158,Eva Coleman,Female,Aashiyana,270828,8772917989,KOTAK,CL,0.20,8,55000,1152.0,880.00,EVA COLEMAN
48,159,Dominic Clark,Male,Jankipuram,236476,7398487833,State Bank of India,EL,0.18,2,86452,4316.0,311.23,DOMINIC CLARK
49,160,Lucy Alexander,Female,Gomti Nagar,385317,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER

In [44]:
#Drop Columns or Rows
df.drop(columns=['AADHAR'], inplace=True)   # Drop a column
df.drop(index=[0, 1], inplace=True)

In [45]:
df

,ID,NAME,GENDER,ADDRESS,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name,Loan_Size
2,113,Luna Sanders,Female,Aminabad,8260860045,PNB,CL,0.12,2,87118,4101.0,209.08,LUNA SANDERS,Medium
3,114,Penelope Jordan,Female,Aashiyana,8307547251,BOB,EL,0.11,9,85813,1255.0,849.55,PENELOPE JORDAN,Medium
4,115,Austin Vo,Male,Jankipuram,7686296906,ICICI Bank,GL,0.20,7,46851,1040.0,655.91,AUSTIN VO,Small
5,116,Joshua Gupta,Male,Gomti Nagar,8835368577,YES,PL,0.20,4,30959,942.0,247.67,JOSHUA GUPTA,Small
6,117,Ruby Barnes,Female,Aminabad,8477605511,UNION,HL,0.20,7,42328,940.0,592.59,RUBY BARNES,Small
7,118,Luke Martin,Male,Aashiyana,8412513269,KOTAK,CL,0.20,2,93444,4756.0,373.78,LUKE MARTIN,Medium
8,119,Easton Bailey,Male,Jankipuram,9170747068,State Bank of India,EL,0.18,3,34587,1250.0,186.77,EASTON BAILEY,Small
9,120,Madeline Walker,Female,Gomti Nagar,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER,Medium
10,121,Savannah Ali,Female,Aminabad,8962904559,PNB,PL,0.12,2,86836,4088.0,208.41,SAVANNAH ALI,Medium
11,122,Camila Rogers,Female,Aashiyana,9115706765,BOB,HL,0.11,10,31253,431.0,343.78,CAMILA ROGERS,Small
12,123,Eli Jones,Male,Jankipuram,9006731602,ICICI Bank,CL,0.20,6,96936,2322.0,1163.23,ELI JONES,Medium
13,124,Everleigh Ng,Female,Gomti Nagar,7741714724,YES,EL,0.20,1,96116,8904.0,192.23,EVERLEIGH NG,Medium
14,125,Robert Yang,Male,Aminabad,8018609222,UNION,GL,0.20,4,50129,1525.0,401.03,ROBERT YANG,Medium
15,126,Isabella Xi,Female,Aashiyana,8321358880,KOTAK,PL,0.20,2,83820,4266.0,335.28,ISABELLA XI,Medium
16,127,Bella Powell,Female,Jankipuram,8180559073,State Bank of India,HL,0.18,1,77600,7114.0,139.68,BELLA POWELL,Medium
17,128,Camila Silva,Female,Gomti Nagar,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA,Medium
18,129,David Barnes,Male,Aminabad,8271922114,PNB,EL,0.12,4,44452,1171.0,213.37,DAVID BARNES,Small
19,130,Adam Dang,Male,Aashiyana,8445337907,BOB,GL,0.11,4,82500,2132.0,363.00,ADAM DANG,Medium
20,131,Elias Alvarado,Male,Jankipuram,8257217138,ICICI Bank,PL,0.20,10,86556,1673.0,1731.12,ELIAS ALVARADO,Medium
21,132,Eva Rivera,Female,Gomti Nagar,8180356851,YES,HL,0.20,7,87364,1940.0,1223.10,EVA RIVERA,Medium
22,133,Logan Rivera,Male,Aminabad,7828839873,UNION,CL,0.20,1,81162,7518.0,162.32,LOGAN RIVERA,Medium
23,134,Leonardo Dixon,Male,Aashiyana,8069324152,KOTAK,EL,0.20,5,54663,1448.0,546.63,LEONARDO DIXON,Medium
24,135,Mateo Her,Male,Jankipuram,7890486222,State Bank of India,GL,0.18,9,52509,985.0,850.65,MATEO HER,Medium
25,136,Jose Henderson,Male,Gomti Nagar,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.55,JOSE HENDERSON,Medium
26,137,Abigail Mejia,Female,Aminabad,7249237561,PNB,HL,0.12,5,35675,794.0,214.05,ABIGAIL MEJIA,Small
27,138,Wyatt Chin,Male,Aashiyana,8004005071,BOB,CL,0.11,5,42218,918.0,232.20,WYATT CHIN,Small
28,139,Carson Lu,Male,Jankipuram,8490807099,ICICI Bank,EL,0.20,8,98229,2058.0,1571.66,CARSON LU,Medium
29,140,Dylan Choi,Male,Gomti Nagar,8582579396,YES,GL,0.20,7,78580,1745.0,1100.12,DYLAN CHOI,Medium
30,141,Ezekiel Kumar,Male,Aminabad,9408619589,UNION,PL,0.20,5,80555,2134.0,805.55,EZEKIEL KUMAR,Medium
31,142,Dominic Guzman,Male,Aashiyana,7469867801,KOTAK,HL,0.20,8,46081,966.0,737.30,DOMINIC GUZMAN,Small
32,143,Angel Powell,Male,Jankipuram,8992428483,State Bank of India,CL,0.18,1,39922,3660.0,71.86,ANGEL POWELL,Small
33,144,Mateo Vu,Male,Gomti Nagar,7651412039,HDFC,EL,0.18,10,54371,980.0,978.68,MATEO VU,Medium
34,145,Caroline Jenkins,Female,Aminabad,8581970606,PNB,GL,0.12,2,73440,3457.0,176.26,CAROLINE JENKINS,Medium
35,146,Nora Brown,Female,Aashiyana,7961188785,BOB,PL,0.11,6,27988,533.0,184.72,NORA BROWN,Small
36,147,Adeline Huang,Female,Jankipuram,9257124480,ICICI Bank,HL,0.20,7,33782,750.0,472.95,ADELINE HUANG,Small
37,148,Jackson Perry,Male,Gomti Nagar,7280368666,YES,CL,0.20,2,48047,2445.0,192.19,JACKSON PERRY,Small
38,149,Riley Padilla,Female,Aminabad,9043676825,UNION,EL,0.20,1,89285,8271.0,178.57,RILEY PADILLA,Medium
39,150,Leah Pena,Female,Aashiyana,7605821528,KOTAK,GL,0.20,3,45151,1678.0,270.91,LEAH PENA,Small
40,151,Owen Lam,Male,Jankipuram,8907901812,State Bank of India,PL,0.18,8,28385,560.0,408.74,OWEN LAM,Small
41,152,Kennedy Foster,Female,Gomti Nagar,7971039531,HDFC,HL,0.18,8,39711,783.0,571.84,KENNEDY FOSTER,Small
42,153,John Moore,Male,Aminabad,8441104809,PNB,CL,0.12,7,69399,1225.0,582.95,JOHN MOORE,Medium
43,154,William Vu,Male,Aashiyana,8973220080,BOB,EL,0.11,8,33879,532.0,298.14,WILLIAM VU,Small
44,155,Sadie Washington,Female,Jankipuram,9177879896,ICICI Bank,GL,0.20,8,32753,686.0,524.05,SADIE WASHINGTON,Small
45,156,Gabriel Holmes,Male,Gomti Nagar,8306537926,YES,PL,0.20,5,74156,1965.0,741.56,GABRIEL HOLMES,Medium
46,157,Wyatt Rojas,Male,Aminabad,7885034254,UNION,HL,0.20,10,62010,1198.0,1240.20,WYATT ROJAS,Medium
47,158,Eva Coleman,Female,Aashiyana,8772917989,KOTAK,CL,0.20,8,55000,1152.0,880.00,EVA COLEMAN,Medium
48,159,Dominic Clark,Male,Jankipuram,7398487833,State Bank of India,EL,0.18,2,86452,4316.0,311.23,DOMINIC CLARK,Medium
49,160,Lucy Alexander,Female,Gomti Nagar,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER,Medium

In [46]:
#Filter Using isin()
df[df['BANK'].isin(['SBI', 'HDFC'])]

,ID,NAME,GENDER,ADDRESS,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name,Loan_Size
9,120,Madeline Walker,Female,Gomti Nagar,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER,Medium
17,128,Camila Silva,Female,Gomti Nagar,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA,Medium
25,136,Jose Henderson,Male,Gomti Nagar,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.55,JOSE HENDERSON,Medium
33,144,Mateo Vu,Male,Gomti Nagar,7651412039,HDFC,EL,0.18,10,54371,980.0,978.68,MATEO VU,Medium
41,152,Kennedy Foster,Female,Gomti Nagar,7971039531,HDFC,HL,0.18,8,39711,783.0,571.84,KENNEDY FOSTER,Small
49,160,Lucy Alexander,Female,Gomti Nagar,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER,Medium

In [48]:
#Conditional Column with np.where() (alternative to apply)
import numpy as np
df['EMI_Status'] = np.where(df['EMI'] > 2000, 'High EMI', 'Low EMI')
df

,ID,NAME,GENDER,ADDRESS,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name,Loan_Size,EMI_Status
2,113,Luna Sanders,Female,Aminabad,8260860045,PNB,CL,0.12,2,87118,4101.0,209.08,LUNA SANDERS,Medium,High EMI
3,114,Penelope Jordan,Female,Aashiyana,8307547251,BOB,EL,0.11,9,85813,1255.0,849.55,PENELOPE JORDAN,Medium,Low EMI
4,115,Austin Vo,Male,Jankipuram,7686296906,ICICI Bank,GL,0.20,7,46851,1040.0,655.91,AUSTIN VO,Small,Low EMI
5,116,Joshua Gupta,Male,Gomti Nagar,8835368577,YES,PL,0.20,4,30959,942.0,247.67,JOSHUA GUPTA,Small,Low EMI
6,117,Ruby Barnes,Female,Aminabad,8477605511,UNION,HL,0.20,7,42328,940.0,592.59,RUBY BARNES,Small,Low EMI
7,118,Luke Martin,Male,Aashiyana,8412513269,KOTAK,CL,0.20,2,93444,4756.0,373.78,LUKE MARTIN,Medium,High EMI
8,119,Easton Bailey,Male,Jankipuram,9170747068,State Bank of India,EL,0.18,3,34587,1250.0,186.77,EASTON BAILEY,Small,Low EMI
9,120,Madeline Walker,Female,Gomti Nagar,8766368873,HDFC,GL,0.18,7,81500,1713.0,1026.90,MADELINE WALKER,Medium,Low EMI
10,121,Savannah Ali,Female,Aminabad,8962904559,PNB,PL,0.12,2,86836,4088.0,208.41,SAVANNAH ALI,Medium,High EMI
11,122,Camila Rogers,Female,Aashiyana,9115706765,BOB,HL,0.11,10,31253,431.0,343.78,CAMILA ROGERS,Small,Low EMI
12,123,Eli Jones,Male,Jankipuram,9006731602,ICICI Bank,CL,0.20,6,96936,2322.0,1163.23,ELI JONES,Medium,High EMI
13,124,Everleigh Ng,Female,Gomti Nagar,7741714724,YES,EL,0.20,1,96116,8904.0,192.23,EVERLEIGH NG,Medium,High EMI
14,125,Robert Yang,Male,Aminabad,8018609222,UNION,GL,0.20,4,50129,1525.0,401.03,ROBERT YANG,Medium,Low EMI
15,126,Isabella Xi,Female,Aashiyana,8321358880,KOTAK,PL,0.20,2,83820,4266.0,335.28,ISABELLA XI,Medium,High EMI
16,127,Bella Powell,Female,Jankipuram,8180559073,State Bank of India,HL,0.18,1,77600,7114.0,139.68,BELLA POWELL,Medium,High EMI
17,128,Camila Silva,Female,Gomti Nagar,8970158939,HDFC,CL,0.18,3,89721,3244.0,484.49,CAMILA SILVA,Medium,High EMI
18,129,David Barnes,Male,Aminabad,8271922114,PNB,EL,0.12,4,44452,1171.0,213.37,DAVID BARNES,Small,Low EMI
19,130,Adam Dang,Male,Aashiyana,8445337907,BOB,GL,0.11,4,82500,2132.0,363.00,ADAM DANG,Medium,High EMI
20,131,Elias Alvarado,Male,Jankipuram,8257217138,ICICI Bank,PL,0.20,10,86556,1673.0,1731.12,ELIAS ALVARADO,Medium,Low EMI
21,132,Eva Rivera,Female,Gomti Nagar,8180356851,YES,HL,0.20,7,87364,1940.0,1223.10,EVA RIVERA,Medium,Low EMI
22,133,Logan Rivera,Male,Aminabad,7828839873,UNION,CL,0.20,1,81162,7518.0,162.32,LOGAN RIVERA,Medium,High EMI
23,134,Leonardo Dixon,Male,Aashiyana,8069324152,KOTAK,EL,0.20,5,54663,1448.0,546.63,LEONARDO DIXON,Medium,Low EMI
24,135,Mateo Her,Male,Jankipuram,7890486222,State Bank of India,GL,0.18,9,52509,985.0,850.65,MATEO HER,Medium,Low EMI
25,136,Jose Henderson,Male,Gomti Nagar,8175409710,HDFC,PL,0.18,2,50154,2504.0,180.55,JOSE HENDERSON,Medium,High EMI
26,137,Abigail Mejia,Female,Aminabad,7249237561,PNB,HL,0.12,5,35675,794.0,214.05,ABIGAIL MEJIA,Small,Low EMI
27,138,Wyatt Chin,Male,Aashiyana,8004005071,BOB,CL,0.11,5,42218,918.0,232.20,WYATT CHIN,Small,Low EMI
28,139,Carson Lu,Male,Jankipuram,8490807099,ICICI Bank,EL,0.20,8,98229,2058.0,1571.66,CARSON LU,Medium,High EMI
29,140,Dylan Choi,Male,Gomti Nagar,8582579396,YES,GL,0.20,7,78580,1745.0,1100.12,DYLAN CHOI,Medium,Low EMI
30,141,Ezekiel Kumar,Male,Aminabad,9408619589,UNION,PL,0.20,5,80555,2134.0,805.55,EZEKIEL KUMAR,Medium,High EMI
31,142,Dominic Guzman,Male,Aashiyana,7469867801,KOTAK,HL,0.20,8,46081,966.0,737.30,DOMINIC GUZMAN,Small,Low EMI
32,143,Angel Powell,Male,Jankipuram,8992428483,State Bank of India,CL,0.18,1,39922,3660.0,71.86,ANGEL POWELL,Small,High EMI
33,144,Mateo Vu,Male,Gomti Nagar,7651412039,HDFC,EL,0.18,10,54371,980.0,978.68,MATEO VU,Medium,Low EMI
34,145,Caroline Jenkins,Female,Aminabad,8581970606,PNB,GL,0.12,2,73440,3457.0,176.26,CAROLINE JENKINS,Medium,High EMI
35,146,Nora Brown,Female,Aashiyana,7961188785,BOB,PL,0.11,6,27988,533.0,184.72,NORA BROWN,Small,Low EMI
36,147,Adeline Huang,Female,Jankipuram,9257124480,ICICI Bank,HL,0.20,7,33782,750.0,472.95,ADELINE HUANG,Small,Low EMI
37,148,Jackson Perry,Male,Gomti Nagar,7280368666,YES,CL,0.20,2,48047,2445.0,192.19,JACKSON PERRY,Small,High EMI
38,149,Riley Padilla,Female,Aminabad,9043676825,UNION,EL,0.20,1,89285,8271.0,178.57,RILEY PADILLA,Medium,High EMI
39,150,Leah Pena,Female,Aashiyana,7605821528,KOTAK,GL,0.20,3,45151,1678.0,270.91,LEAH PENA,Small,Low EMI
40,151,Owen Lam,Male,Jankipuram,8907901812,State Bank of India,PL,0.18,8,28385,560.0,408.74,OWEN LAM,Small,Low EMI
41,152,Kennedy Foster,Female,Gomti Nagar,7971039531,HDFC,HL,0.18,8,39711,783.0,571.84,KENNEDY FOSTER,Small,Low EMI
42,153,John Moore,Male,Aminabad,8441104809,PNB,CL,0.12,7,69399,1225.0,582.95,JOHN MOORE,Medium,Low EMI
43,154,William Vu,Male,Aashiyana,8973220080,BOB,EL,0.11,8,33879,532.0,298.14,WILLIAM VU,Small,Low EMI
44,155,Sadie Washington,Female,Jankipuram,9177879896,ICICI Bank,GL,0.20,8,32753,686.0,524.05,SADIE WASHINGTON,Small,Low EMI
45,156,Gabriel Holmes,Male,Gomti Nagar,8306537926,YES,PL,0.20,5,74156,1965.0,741.56,GABRIEL HOLMES,Medium,Low EMI
46,157,Wyatt Rojas,Male,Aminabad,7885034254,UNION,HL,0.20,10,62010,1198.0,1240.20,WYATT ROJAS,Medium,Low EMI
47,158,Eva Coleman,Female,Aashiyana,8772917989,KOTAK,CL,0.20,8,55000,1152.0,880.00,EVA COLEMAN,Medium,Low EMI
48,159,Dominic Clark,Male,Jankipuram,7398487833,State Bank of India,EL,0.18,2,86452,4316.0,311.23,DOMINIC CLARK,Medium,High EMI
49,160,Lucy Alexander,Female,Gomti Nagar,7540127982,HDFC,GL,0.18,3,80110,2896.0,432.59,LUCY ALEXANDER,Medium,High EMI

In [49]:
#Query Syntax (Readable Filter)
df.query("GENDER == 'Female' and BANK == 'PNB'")

,ID,NAME,GENDER,ADDRESS,CONTACT,BANK,Loan,Rate,TIME,AMOUNT,EMI,Interest,Full_Name,Loan_Size,EMI_Status
2,113,Luna Sanders,Female,Aminabad,8260860045,PNB,CL,0.12,2,87118,4101.0,209.08,LUNA SANDERS,Medium,High EMI
10,121,Savannah Ali,Female,Aminabad,8962904559,PNB,PL,0.12,2,86836,4088.0,208.41,SAVANNAH ALI,Medium,High EMI
26,137,Abigail Mejia,Female,Aminabad,7249237561,PNB,HL,0.12,5,35675,794.0,214.05,ABIGAIL MEJIA,Small,Low EMI
34,145,Caroline Jenkins,Female,Aminabad,8581970606,PNB,GL,0.12,2,73440,3457.0,176.26,CAROLINE JENKINS,Medium,High EMI